# Generated by Django 4.0.3 on 2022-09-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_user_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=222, null=True, unique=True)),
            ],
            options={
                'db_table': 'role_list',
                'ordering': ['pk'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.role')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
            options={
                'db_table': 'userpermission',
                'ordering': ['pk'],
                'managed': True,
            },
        ),
    ]
