# Generated by Django 4.0.3 on 2022-09-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
