# Generated by Django 4.0.3 on 2022-09-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_book_added_by_remove_book_book_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
